<?xml version="1.0" encoding="utf-8"?><Database Name="nop-2.80" Class="Nop280DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=localhost;Initial Catalog=nop-2.80;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="nop_2_80ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Product" Member="Products">
    <Type Name="Product">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(400) NOT NULL" CanBeNull="false" />
      <Column Name="ShortDescription" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="FullDescription" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="AdminComment" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ProductTemplateId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ShowOnHomePage" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="MetaKeywords" Type="System.String" DbType="NVarChar(400)" CanBeNull="true" />
      <Column Name="MetaDescription" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="MetaTitle" Type="System.String" DbType="NVarChar(400)" CanBeNull="true" />
      <Column Name="AllowCustomerReviews" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ApprovedRatingSum" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NotApprovedRatingSum" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ApprovedTotalReviews" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NotApprovedTotalReviews" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SubjectToAcl" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Published" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Deleted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CreatedOnUtc" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UpdatedOnUtc" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="Product_Product_SpecificationAttribute_Mapping" Member="Product_SpecificationAttribute_Mappings" ThisKey="Id" OtherKey="ProductId" Type="Product_SpecificationAttribute_Mapping" />
      <Association Name="Product_Product_Category_Mapping" Member="Product_Category_Mappings" ThisKey="Id" OtherKey="ProductId" Type="Product_Category_Mapping" />
      <Association Name="Product_Product_Manufacturer_Mapping" Member="Product_Manufacturer_Mappings" ThisKey="Id" OtherKey="ProductId" Type="Product_Manufacturer_Mapping" />
      <Association Name="Product_Product_ProductTag_Mapping" Member="Product_ProductTag_Mappings" ThisKey="Id" OtherKey="Product_Id" Type="Product_ProductTag_Mapping" />
      <Association Name="Product_Product_Picture_Mapping" Member="Product_Picture_Mappings" ThisKey="Id" OtherKey="ProductId" Type="Product_Picture_Mapping" />
      <Association Name="Product_ProductVariant" Member="ProductVariants" ThisKey="Id" OtherKey="ProductId" Type="ProductVariant" />
    </Type>
  </Table>
  <Table Name="dbo.Product_SpecificationAttribute_Mapping" Member="Product_SpecificationAttribute_Mappings">
    <Type Name="Product_SpecificationAttribute_Mapping">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ProductId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SpecificationAttributeOptionId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CustomValue" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="AllowFiltering" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ShowOnProductPage" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DisplayOrder" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Product_Product_SpecificationAttribute_Mapping" Member="Product" ThisKey="ProductId" OtherKey="Id" Type="Product" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="SpecificationAttributeOption_Product_SpecificationAttribute_Mapping" Member="SpecificationAttributeOption" ThisKey="SpecificationAttributeOptionId" OtherKey="Id" Type="SpecificationAttributeOption" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Product_Category_Mapping" Member="Product_Category_Mappings">
    <Type Name="Product_Category_Mapping">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ProductId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CategoryId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IsFeaturedProduct" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DisplayOrder" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Product_Product_Category_Mapping" Member="Product" ThisKey="ProductId" OtherKey="Id" Type="Product" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="Category_Product_Category_Mapping" Member="Category" ThisKey="CategoryId" OtherKey="Id" Type="Category" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Product_Manufacturer_Mapping" Member="Product_Manufacturer_Mappings">
    <Type Name="Product_Manufacturer_Mapping">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ProductId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ManufacturerId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IsFeaturedProduct" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DisplayOrder" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Product_Product_Manufacturer_Mapping" Member="Product" ThisKey="ProductId" OtherKey="Id" Type="Product" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="Manufacturer_Product_Manufacturer_Mapping" Member="Manufacturer" ThisKey="ManufacturerId" OtherKey="Id" Type="Manufacturer" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Product_ProductTag_Mapping" Member="Product_ProductTag_Mappings">
    <Type Name="Product_ProductTag_Mapping">
      <Column Name="ProductTag_Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Product_Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Product_Product_ProductTag_Mapping" Member="Product" ThisKey="Product_Id" OtherKey="Id" Type="Product" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="ProductTag_Product_ProductTag_Mapping" Member="ProductTag" ThisKey="ProductTag_Id" OtherKey="Id" Type="ProductTag" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ProductTag" Member="ProductTags">
    <Type Name="ProductTag">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(400) NOT NULL" CanBeNull="false" />
      <Column Name="ProductCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="ProductTag_Product_ProductTag_Mapping" Member="Product_ProductTag_Mappings" ThisKey="Id" OtherKey="ProductTag_Id" Type="Product_ProductTag_Mapping" />
    </Type>
  </Table>
  <Table Name="dbo.Product_Picture_Mapping" Member="Product_Picture_Mappings">
    <Type Name="Product_Picture_Mapping">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ProductId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PictureId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DisplayOrder" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Product_Product_Picture_Mapping" Member="Product" ThisKey="ProductId" OtherKey="Id" Type="Product" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="Picture_Product_Picture_Mapping" Member="Picture" ThisKey="PictureId" OtherKey="Id" Type="Picture" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Picture" Member="Pictures">
    <Type Name="Picture">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PictureBinary" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="MimeType" Type="System.String" DbType="NVarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="SeoFilename" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="IsNew" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Picture_Product_Picture_Mapping" Member="Product_Picture_Mappings" ThisKey="Id" OtherKey="PictureId" Type="Product_Picture_Mapping" />
    </Type>
  </Table>
  <Table Name="dbo.ProductVariant" Member="ProductVariants">
    <Type Name="ProductVariant">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ProductId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(400)" CanBeNull="true" />
      <Column Name="Sku" Type="System.String" DbType="NVarChar(400)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="AdminComment" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ManufacturerPartNumber" Type="System.String" DbType="NVarChar(400)" CanBeNull="true" />
      <Column Name="Gtin" Type="System.String" DbType="NVarChar(400)" CanBeNull="true" />
      <Column Name="IsGiftCard" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="GiftCardTypeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RequireOtherProducts" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="RequiredProductVariantIds" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="AutomaticallyAddRequiredProductVariants" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsDownload" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DownloadId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UnlimitedDownloads" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="MaxNumberOfDownloads" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DownloadExpirationDays" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DownloadActivationTypeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="HasSampleDownload" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="SampleDownloadId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="HasUserAgreement" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="UserAgreementText" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="IsRecurring" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="RecurringCycleLength" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RecurringCyclePeriodId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RecurringTotalCycles" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IsShipEnabled" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsFreeShipping" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="AdditionalShippingCharge" Type="System.Decimal" DbType="Decimal(18,4) NOT NULL" CanBeNull="false" />
      <Column Name="IsTaxExempt" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="TaxCategoryId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ManageInventoryMethodId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StockQuantity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DisplayStockAvailability" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DisplayStockQuantity" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="MinStockQuantity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LowStockActivityId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NotifyAdminForQuantityBelow" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BackorderModeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AllowBackInStockSubscriptions" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="OrderMinimumQuantity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="OrderMaximumQuantity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AllowedQuantities" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="DisableBuyButton" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DisableWishlistButton" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="AvailableForPreOrder" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CallForPrice" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Price" Type="System.Decimal" DbType="Decimal(18,4) NOT NULL" CanBeNull="false" />
      <Column Name="OldPrice" Type="System.Decimal" DbType="Decimal(18,4) NOT NULL" CanBeNull="false" />
      <Column Name="ProductCost" Type="System.Decimal" DbType="Decimal(18,4) NOT NULL" CanBeNull="false" />
      <Column Name="SpecialPrice" Type="System.Decimal" DbType="Decimal(18,4)" CanBeNull="true" />
      <Column Name="SpecialPriceStartDateTimeUtc" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SpecialPriceEndDateTimeUtc" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CustomerEntersPrice" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="MinimumCustomerEnteredPrice" Type="System.Decimal" DbType="Decimal(18,4) NOT NULL" CanBeNull="false" />
      <Column Name="MaximumCustomerEnteredPrice" Type="System.Decimal" DbType="Decimal(18,4) NOT NULL" CanBeNull="false" />
      <Column Name="HasTierPrices" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="HasDiscountsApplied" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Weight" Type="System.Decimal" DbType="Decimal(18,4) NOT NULL" CanBeNull="false" />
      <Column Name="Length" Type="System.Decimal" DbType="Decimal(18,4) NOT NULL" CanBeNull="false" />
      <Column Name="Width" Type="System.Decimal" DbType="Decimal(18,4) NOT NULL" CanBeNull="false" />
      <Column Name="Height" Type="System.Decimal" DbType="Decimal(18,4) NOT NULL" CanBeNull="false" />
      <Column Name="PictureId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AvailableStartDateTimeUtc" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="AvailableEndDateTimeUtc" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Published" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Deleted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DisplayOrder" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreatedOnUtc" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UpdatedOnUtc" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="ProductVariant_ProductVariant_ProductAttribute_Mapping" Member="ProductVariant_ProductAttribute_Mappings" ThisKey="Id" OtherKey="ProductVariantId" Type="ProductVariant_ProductAttribute_Mapping" />
      <Association Name="ProductVariant_ProductVariantAttributeCombination" Member="ProductVariantAttributeCombinations" ThisKey="Id" OtherKey="ProductVariantId" Type="ProductVariantAttributeCombination" />
      <Association Name="ProductVariant_TierPrice" Member="TierPrices" ThisKey="Id" OtherKey="ProductVariantId" Type="TierPrice" />
      <Association Name="Product_ProductVariant" Member="Product" ThisKey="ProductId" OtherKey="Id" Type="Product" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="TaxCategory_ProductVariant" Member="TaxCategory" ThisKey="TaxCategoryId" OtherKey="Id" Type="TaxCategory" IsForeignKey="true" />
      <Association Name="Download_ProductVariant" Member="Download" ThisKey="DownloadId" OtherKey="Id" Type="Download" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ProductVariant_ProductAttribute_Mapping" Member="ProductVariant_ProductAttribute_Mappings">
    <Type Name="ProductVariant_ProductAttribute_Mapping">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ProductVariantId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProductAttributeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TextPrompt" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="IsRequired" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="AttributeControlTypeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DisplayOrder" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="ProductVariant_ProductAttribute_Mapping_ProductVariantAttributeValue" Member="ProductVariantAttributeValues" ThisKey="Id" OtherKey="ProductVariantAttributeId" Type="ProductVariantAttributeValue" />
      <Association Name="ProductVariant_ProductVariant_ProductAttribute_Mapping" Member="ProductVariant" ThisKey="ProductVariantId" OtherKey="Id" Type="ProductVariant" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="ProductAttribute_ProductVariant_ProductAttribute_Mapping" Member="ProductAttribute" ThisKey="ProductAttributeId" OtherKey="Id" Type="ProductAttribute" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ProductVariantAttributeCombination" Member="ProductVariantAttributeCombinations">
    <Type Name="ProductVariantAttributeCombination">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ProductVariantId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AttributesXml" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="StockQuantity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AllowOutOfStockOrders" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Sku" Type="System.String" DbType="NVarChar(400)" CanBeNull="true" />
      <Column Name="ManufacturerPartNumber" Type="System.String" DbType="NVarChar(400)" CanBeNull="true" />
      <Column Name="Gtin" Type="System.String" DbType="NVarChar(400)" CanBeNull="true" />
      <Association Name="ProductVariant_ProductVariantAttributeCombination" Member="ProductVariant" ThisKey="ProductVariantId" OtherKey="Id" Type="ProductVariant" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ProductVariantAttributeValue" Member="ProductVariantAttributeValues">
    <Type Name="ProductVariantAttributeValue">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ProductVariantAttributeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(400) NOT NULL" CanBeNull="false" />
      <Column Name="ColorSquaresRgb" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="PriceAdjustment" Type="System.Decimal" DbType="Decimal(18,4) NOT NULL" CanBeNull="false" />
      <Column Name="WeightAdjustment" Type="System.Decimal" DbType="Decimal(18,4) NOT NULL" CanBeNull="false" />
      <Column Name="IsPreSelected" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DisplayOrder" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="ProductVariant_ProductAttribute_Mapping_ProductVariantAttributeValue" Member="ProductVariant_ProductAttribute_Mapping" ThisKey="ProductVariantAttributeId" OtherKey="Id" Type="ProductVariant_ProductAttribute_Mapping" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ProductAttribute" Member="ProductAttributes">
    <Type Name="ProductAttribute">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="ProductAttribute_ProductVariant_ProductAttribute_Mapping" Member="ProductVariant_ProductAttribute_Mappings" ThisKey="Id" OtherKey="ProductAttributeId" Type="ProductVariant_ProductAttribute_Mapping" />
    </Type>
  </Table>
  <Table Name="dbo.Manufacturer" Member="Manufacturers">
    <Type Name="Manufacturer">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(400) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ManufacturerTemplateId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MetaKeywords" Type="System.String" DbType="NVarChar(400)" CanBeNull="true" />
      <Column Name="MetaDescription" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="MetaTitle" Type="System.String" DbType="NVarChar(400)" CanBeNull="true" />
      <Column Name="PictureId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PageSize" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AllowCustomersToSelectPageSize" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="PageSizeOptions" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="PriceRanges" Type="System.String" DbType="NVarChar(400)" CanBeNull="true" />
      <Column Name="SubjectToAcl" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Published" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Deleted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DisplayOrder" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreatedOnUtc" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UpdatedOnUtc" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="Manufacturer_Product_Manufacturer_Mapping" Member="Product_Manufacturer_Mappings" ThisKey="Id" OtherKey="ManufacturerId" Type="Product_Manufacturer_Mapping" />
    </Type>
  </Table>
  <Table Name="dbo.Category" Member="Categories">
    <Type Name="Category">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(400) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CategoryTemplateId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MetaKeywords" Type="System.String" DbType="NVarChar(400)" CanBeNull="true" />
      <Column Name="MetaDescription" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="MetaTitle" Type="System.String" DbType="NVarChar(400)" CanBeNull="true" />
      <Column Name="ParentCategoryId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PictureId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PageSize" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AllowCustomersToSelectPageSize" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="PageSizeOptions" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="PriceRanges" Type="System.String" DbType="NVarChar(400)" CanBeNull="true" />
      <Column Name="ShowOnHomePage" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="HasDiscountsApplied" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="SubjectToAcl" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Published" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Deleted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DisplayOrder" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreatedOnUtc" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UpdatedOnUtc" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="Category_Product_Category_Mapping" Member="Product_Category_Mappings" ThisKey="Id" OtherKey="CategoryId" Type="Product_Category_Mapping" />
    </Type>
  </Table>
  <Table Name="dbo.SpecificationAttributeOption" Member="SpecificationAttributeOptions">
    <Type Name="SpecificationAttributeOption">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SpecificationAttributeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="DisplayOrder" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="SpecificationAttributeOption_Product_SpecificationAttribute_Mapping" Member="Product_SpecificationAttribute_Mappings" ThisKey="Id" OtherKey="SpecificationAttributeOptionId" Type="Product_SpecificationAttribute_Mapping" />
      <Association Name="SpecificationAttribute_SpecificationAttributeOption" Member="SpecificationAttribute" ThisKey="SpecificationAttributeId" OtherKey="Id" Type="SpecificationAttribute" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.SpecificationAttribute" Member="SpecificationAttributes">
    <Type Name="SpecificationAttribute">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="DisplayOrder" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="SpecificationAttribute_SpecificationAttributeOption" Member="SpecificationAttributeOptions" ThisKey="Id" OtherKey="SpecificationAttributeId" Type="SpecificationAttributeOption" />
    </Type>
  </Table>
  <Table Name="dbo.TaxCategory" Member="TaxCategories">
    <Type Name="TaxCategory">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(400) NOT NULL" CanBeNull="false" />
      <Column Name="DisplayOrder" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="TaxCategory_ProductVariant" Member="ProductVariants" ThisKey="Id" OtherKey="TaxCategoryId" Type="ProductVariant" />
      <Association Name="TaxRate_TaxCategory" Member="TaxRate" ThisKey="Id" OtherKey="TaxCategoryId" Type="TaxRate" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TaxRate" Member="TaxRates">
    <Type Name="TaxRate">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TaxCategoryId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CountryId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StateProvinceId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Zip" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Percentage" Type="System.Decimal" DbType="Decimal(18,4) NOT NULL" CanBeNull="false" />
      <Association Name="TaxRate_TaxCategory" Member="TaxCategories" ThisKey="TaxCategoryId" OtherKey="Id" Type="TaxCategory" />
      <Association Name="StateProvince_TaxRate" Member="StateProvince" ThisKey="StateProvinceId" OtherKey="Id" Type="StateProvince" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Country" Member="Countries">
    <Type Name="Country">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="AllowsBilling" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="AllowsShipping" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="TwoLetterIsoCode" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="ThreeLetterIsoCode" Type="System.String" DbType="NVarChar(3)" CanBeNull="true" />
      <Column Name="NumericIsoCode" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SubjectToVat" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Published" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DisplayOrder" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Country_StateProvince" Member="StateProvinces" ThisKey="Id" OtherKey="CountryId" Type="StateProvince" />
      <Association Name="Country_Address" Member="Addresses" ThisKey="Id" OtherKey="CountryId" Type="Address" />
    </Type>
  </Table>
  <Table Name="dbo.StateProvince" Member="StateProvinces">
    <Type Name="StateProvince">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CountryId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Abbreviation" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Published" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DisplayOrder" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="StateProvince_TaxRate" Member="TaxRates" ThisKey="Id" OtherKey="StateProvinceId" Type="TaxRate" />
      <Association Name="StateProvince_Address" Member="Addresses" ThisKey="Id" OtherKey="StateProvinceId" Type="Address" />
      <Association Name="Country_StateProvince" Member="Country" ThisKey="CountryId" OtherKey="Id" Type="Country" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TierPrice" Member="TierPrices">
    <Type Name="TierPrice">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ProductVariantId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CustomerRoleId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Price" Type="System.Decimal" DbType="Decimal(18,4) NOT NULL" CanBeNull="false" />
      <Association Name="ProductVariant_TierPrice" Member="ProductVariant" ThisKey="ProductVariantId" OtherKey="Id" Type="ProductVariant" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Download" Member="Downloads">
    <Type Name="Download">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DownloadGuid" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="UseDownloadUrl" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DownloadUrl" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DownloadBinary" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ContentType" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Filename" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Extension" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="IsNew" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Download_ProductVariant" Member="ProductVariants" ThisKey="Id" OtherKey="DownloadId" Type="ProductVariant" />
    </Type>
  </Table>
  <Table Name="dbo.CustomerAddresses" Member="CustomerAddresses">
    <Type Name="CustomerAddress">
      <Column Name="Customer_Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Address_Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Customer_CustomerAddress" Member="Customer" ThisKey="Customer_Id" OtherKey="Id" Type="Customer" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="Address_CustomerAddress" Member="Address" ThisKey="Address_Id" OtherKey="Id" Type="Address" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Customer" Member="Customers">
    <Type Name="Customer">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CustomerGuid" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="PasswordFormatId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PasswordSalt" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="AdminComment" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LanguageId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CurrencyId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TaxDisplayTypeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IsTaxExempt" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="VatNumber" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="VatNumberStatusId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SelectedPaymentMethodSystemName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CheckoutAttributes" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DiscountCouponCode" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="GiftCardCouponCodes" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="UseRewardPointsDuringCheckout" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="TimeZoneId" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="AffiliateId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Deleted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsSystemAccount" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="SystemName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LastIpAddress" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CreatedOnUtc" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LastLoginDateUtc" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LastActivityDateUtc" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="BillingAddress_Id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ShippingAddress_Id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Customer_CustomerAddress" Member="CustomerAddresses" ThisKey="Id" OtherKey="Customer_Id" Type="CustomerAddress" />
      <Association Name="Address_Customer" Member="Address" ThisKey="BillingAddress_Id" OtherKey="Id" Type="Address" IsForeignKey="true" />
      <Association Name="Address_Customer1" Member="Address1" ThisKey="ShippingAddress_Id" OtherKey="Id" Type="Address" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.GenericAttribute" Member="GenericAttributes">
    <Type Name="GenericAttribute">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="EntityId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="KeyGroup" Type="System.String" DbType="NVarChar(400) NOT NULL" CanBeNull="false" />
      <Column Name="[Key]" Member="Key" Type="System.String" DbType="NVarChar(400) NOT NULL" CanBeNull="false" />
      <Column Name="Value" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Address" Member="Addresses">
    <Type Name="Address">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Company" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CountryId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StateProvinceId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Address1" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Address2" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ZipPostalCode" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="PhoneNumber" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="FaxNumber" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CreatedOnUtc" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="Address_CustomerAddress" Member="CustomerAddresses" ThisKey="Id" OtherKey="Address_Id" Type="CustomerAddress" />
      <Association Name="Address_Customer" Member="Customers" ThisKey="Id" OtherKey="BillingAddress_Id" Type="Customer" />
      <Association Name="Address_Customer1" Member="Customers1" ThisKey="Id" OtherKey="ShippingAddress_Id" Type="Customer" />
      <Association Name="Country_Address" Member="Country" ThisKey="CountryId" OtherKey="Id" Type="Country" IsForeignKey="true" />
      <Association Name="StateProvince_Address" Member="StateProvince" ThisKey="StateProvinceId" OtherKey="Id" Type="StateProvince" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.UrlRecord" Member="UrlRecords">
    <Type Name="UrlRecord">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="EntityId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="EntityName" Type="System.String" DbType="NVarChar(400) NOT NULL" CanBeNull="false" />
      <Column Name="Slug" Type="System.String" DbType="NVarChar(400) NOT NULL" CanBeNull="false" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="LanguageId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Setting" Member="Settings">
    <Type Name="Setting">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Value" Type="System.String" DbType="NVarChar(2000) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>