//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MrCMS.PaypointService.API {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://www.secpay.com/java-bin/services/SECCardService", ConfigurationName="API.SECVPN")]
    public interface SECVPN {
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://secvpn.secpay.com) of message refundCardFullRequest does not match the default value (https://www.secpay.com/java-bin/services/SECCardService)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        MrCMS.PaypointService.API.refundCardFullResponse refundCardFull(MrCMS.PaypointService.API.refundCardFullRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://secvpn.secpay.com) of message releaseCardFullRequest does not match the default value (https://www.secpay.com/java-bin/services/SECCardService)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        MrCMS.PaypointService.API.releaseCardFullResponse releaseCardFull(MrCMS.PaypointService.API.releaseCardFullRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://secvpn.secpay.com) of message repeatCardFullAddrRequest does not match the default value (https://www.secpay.com/java-bin/services/SECCardService)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        MrCMS.PaypointService.API.repeatCardFullAddrResponse repeatCardFullAddr(MrCMS.PaypointService.API.repeatCardFullAddrRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://secvpn.secpay.com) of message repeatCardFullRequest does not match the default value (https://www.secpay.com/java-bin/services/SECCardService)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        MrCMS.PaypointService.API.repeatCardFullResponse repeatCardFull(MrCMS.PaypointService.API.repeatCardFullRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://secvpn.secpay.com) of message validateCardFullRequest does not match the default value (https://www.secpay.com/java-bin/services/SECCardService)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        MrCMS.PaypointService.API.validateCardFullResponse validateCardFull(MrCMS.PaypointService.API.validateCardFullRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://secvpn.secpay.com) of message threeDSecureEnrolmentRequestRequest does not match the default value (https://www.secpay.com/java-bin/services/SECCardService)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        MrCMS.PaypointService.API.threeDSecureEnrolmentRequestResponse threeDSecureEnrolmentRequest(MrCMS.PaypointService.API.threeDSecureEnrolmentRequestRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://secvpn.secpay.com) of message threeDSecureAuthorisationRequestRequest does not match the default value (https://www.secpay.com/java-bin/services/SECCardService)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        MrCMS.PaypointService.API.threeDSecureAuthorisationRequestResponse threeDSecureAuthorisationRequest(MrCMS.PaypointService.API.threeDSecureAuthorisationRequestRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://secvpn.secpay.com) of message getReportRequest does not match the default value (https://www.secpay.com/java-bin/services/SECCardService)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        MrCMS.PaypointService.API.getReportResponse getReport(MrCMS.PaypointService.API.getReportRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://secvpn.secpay.com) of message getTZReportRequest does not match the default value (https://www.secpay.com/java-bin/services/SECCardService)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        MrCMS.PaypointService.API.getTZReportResponse getTZReport(MrCMS.PaypointService.API.getTZReportRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://secvpn.secpay.com) of message performTransactionViaAlternatePaymentMethodRequest does not match the default value (https://www.secpay.com/java-bin/services/SECCardService)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        MrCMS.PaypointService.API.performTransactionViaAlternatePaymentMethodResponse performTransactionViaAlternatePaymentMethod(MrCMS.PaypointService.API.performTransactionViaAlternatePaymentMethodRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="refundCardFull", WrapperNamespace="http://secvpn.secpay.com", IsWrapped=true)]
    public partial class refundCardFullRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string mid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string vpn_pswd;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string trans_id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string amount;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string remote_pswd;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public string new_trans_id;
        
        public refundCardFullRequest() {
        }
        
        public refundCardFullRequest(string mid, string vpn_pswd, string trans_id, string amount, string remote_pswd, string new_trans_id) {
            this.mid = mid;
            this.vpn_pswd = vpn_pswd;
            this.trans_id = trans_id;
            this.amount = amount;
            this.remote_pswd = remote_pswd;
            this.new_trans_id = new_trans_id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="refundCardFullResponse", WrapperNamespace="https://www.secpay.com/java-bin/services/SECCardService", IsWrapped=true)]
    public partial class refundCardFullResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string refundCardFullReturn;
        
        public refundCardFullResponse() {
        }
        
        public refundCardFullResponse(string refundCardFullReturn) {
            this.refundCardFullReturn = refundCardFullReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="releaseCardFull", WrapperNamespace="http://secvpn.secpay.com", IsWrapped=true)]
    public partial class releaseCardFullRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string mid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string vpn_pswd;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string trans_id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string amount;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string remote_pswd;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public string new_trans_id;
        
        public releaseCardFullRequest() {
        }
        
        public releaseCardFullRequest(string mid, string vpn_pswd, string trans_id, string amount, string remote_pswd, string new_trans_id) {
            this.mid = mid;
            this.vpn_pswd = vpn_pswd;
            this.trans_id = trans_id;
            this.amount = amount;
            this.remote_pswd = remote_pswd;
            this.new_trans_id = new_trans_id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="releaseCardFullResponse", WrapperNamespace="https://www.secpay.com/java-bin/services/SECCardService", IsWrapped=true)]
    public partial class releaseCardFullResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string releaseCardFullReturn;
        
        public releaseCardFullResponse() {
        }
        
        public releaseCardFullResponse(string releaseCardFullReturn) {
            this.releaseCardFullReturn = releaseCardFullReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="repeatCardFullAddr", WrapperNamespace="http://secvpn.secpay.com", IsWrapped=true)]
    public partial class repeatCardFullAddrRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string mid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string vpn_pswd;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string trans_id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string amount;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string remote_pswd;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public string new_trans_id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=6)]
        public string exp_date;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=7)]
        public string order;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=8)]
        public string bill;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=9)]
        public string ship;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=10)]
        public string options;
        
        public repeatCardFullAddrRequest() {
        }
        
        public repeatCardFullAddrRequest(string mid, string vpn_pswd, string trans_id, string amount, string remote_pswd, string new_trans_id, string exp_date, string order, string bill, string ship, string options) {
            this.mid = mid;
            this.vpn_pswd = vpn_pswd;
            this.trans_id = trans_id;
            this.amount = amount;
            this.remote_pswd = remote_pswd;
            this.new_trans_id = new_trans_id;
            this.exp_date = exp_date;
            this.order = order;
            this.bill = bill;
            this.ship = ship;
            this.options = options;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="repeatCardFullAddrResponse", WrapperNamespace="https://www.secpay.com/java-bin/services/SECCardService", IsWrapped=true)]
    public partial class repeatCardFullAddrResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string repeatCardFullAddrReturn;
        
        public repeatCardFullAddrResponse() {
        }
        
        public repeatCardFullAddrResponse(string repeatCardFullAddrReturn) {
            this.repeatCardFullAddrReturn = repeatCardFullAddrReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="repeatCardFull", WrapperNamespace="http://secvpn.secpay.com", IsWrapped=true)]
    public partial class repeatCardFullRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string mid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string vpn_pswd;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string trans_id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string amount;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string remote_pswd;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public string new_trans_id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=6)]
        public string exp_date;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=7)]
        public string order;
        
        public repeatCardFullRequest() {
        }
        
        public repeatCardFullRequest(string mid, string vpn_pswd, string trans_id, string amount, string remote_pswd, string new_trans_id, string exp_date, string order) {
            this.mid = mid;
            this.vpn_pswd = vpn_pswd;
            this.trans_id = trans_id;
            this.amount = amount;
            this.remote_pswd = remote_pswd;
            this.new_trans_id = new_trans_id;
            this.exp_date = exp_date;
            this.order = order;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="repeatCardFullResponse", WrapperNamespace="https://www.secpay.com/java-bin/services/SECCardService", IsWrapped=true)]
    public partial class repeatCardFullResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string repeatCardFullReturn;
        
        public repeatCardFullResponse() {
        }
        
        public repeatCardFullResponse(string repeatCardFullReturn) {
            this.repeatCardFullReturn = repeatCardFullReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="validateCardFull", WrapperNamespace="http://secvpn.secpay.com", IsWrapped=true)]
    public partial class validateCardFullRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string mid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string vpn_pswd;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string trans_id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string ip;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string name;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public string card_number;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=6)]
        public string amount;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=7)]
        public string expiry_date;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=8)]
        public string issue_number;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=9)]
        public string start_date;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=10)]
        public string order;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=11)]
        public string shipping;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=12)]
        public string billing;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=13)]
        public string options;
        
        public validateCardFullRequest() {
        }
        
        public validateCardFullRequest(string mid, string vpn_pswd, string trans_id, string ip, string name, string card_number, string amount, string expiry_date, string issue_number, string start_date, string order, string shipping, string billing, string options) {
            this.mid = mid;
            this.vpn_pswd = vpn_pswd;
            this.trans_id = trans_id;
            this.ip = ip;
            this.name = name;
            this.card_number = card_number;
            this.amount = amount;
            this.expiry_date = expiry_date;
            this.issue_number = issue_number;
            this.start_date = start_date;
            this.order = order;
            this.shipping = shipping;
            this.billing = billing;
            this.options = options;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="validateCardFullResponse", WrapperNamespace="https://www.secpay.com/java-bin/services/SECCardService", IsWrapped=true)]
    public partial class validateCardFullResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string validateCardFullReturn;
        
        public validateCardFullResponse() {
        }
        
        public validateCardFullResponse(string validateCardFullReturn) {
            this.validateCardFullReturn = validateCardFullReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="threeDSecureEnrolmentRequest", WrapperNamespace="http://secvpn.secpay.com", IsWrapped=true)]
    public partial class threeDSecureEnrolmentRequestRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string mid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string vpn_pswd;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string trans_id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string ip;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string name;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public string card_number;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=6)]
        public string amount;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=7)]
        public string expiry_date;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=8)]
        public string issue_number;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=9)]
        public string start_date;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=10)]
        public string order;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=11)]
        public string shipping;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=12)]
        public string billing;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=13)]
        public string options;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=14)]
        public string device_category;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=15)]
        public string accept_headers;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=16)]
        public string user_agent;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=17)]
        public string mpi_merchant_name;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=18)]
        public string mpi_merchant_url;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=19)]
        public string mpi_description;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=20)]
        public string purchaseRecurringFrequency;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=21)]
        public string purchaseRecurringExpiry;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=22)]
        public string purchaseInstallments;
        
        public threeDSecureEnrolmentRequestRequest() {
        }
        
        public threeDSecureEnrolmentRequestRequest(
                    string mid, 
                    string vpn_pswd, 
                    string trans_id, 
                    string ip, 
                    string name, 
                    string card_number, 
                    string amount, 
                    string expiry_date, 
                    string issue_number, 
                    string start_date, 
                    string order, 
                    string shipping, 
                    string billing, 
                    string options, 
                    string device_category, 
                    string accept_headers, 
                    string user_agent, 
                    string mpi_merchant_name, 
                    string mpi_merchant_url, 
                    string mpi_description, 
                    string purchaseRecurringFrequency, 
                    string purchaseRecurringExpiry, 
                    string purchaseInstallments) {
            this.mid = mid;
            this.vpn_pswd = vpn_pswd;
            this.trans_id = trans_id;
            this.ip = ip;
            this.name = name;
            this.card_number = card_number;
            this.amount = amount;
            this.expiry_date = expiry_date;
            this.issue_number = issue_number;
            this.start_date = start_date;
            this.order = order;
            this.shipping = shipping;
            this.billing = billing;
            this.options = options;
            this.device_category = device_category;
            this.accept_headers = accept_headers;
            this.user_agent = user_agent;
            this.mpi_merchant_name = mpi_merchant_name;
            this.mpi_merchant_url = mpi_merchant_url;
            this.mpi_description = mpi_description;
            this.purchaseRecurringFrequency = purchaseRecurringFrequency;
            this.purchaseRecurringExpiry = purchaseRecurringExpiry;
            this.purchaseInstallments = purchaseInstallments;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="threeDSecureEnrolmentRequestResponse", WrapperNamespace="https://www.secpay.com/java-bin/services/SECCardService", IsWrapped=true)]
    public partial class threeDSecureEnrolmentRequestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string threeDSecureEnrolmentRequestReturn;
        
        public threeDSecureEnrolmentRequestResponse() {
        }
        
        public threeDSecureEnrolmentRequestResponse(string threeDSecureEnrolmentRequestReturn) {
            this.threeDSecureEnrolmentRequestReturn = threeDSecureEnrolmentRequestReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="threeDSecureAuthorisationRequest", WrapperNamespace="http://secvpn.secpay.com", IsWrapped=true)]
    public partial class threeDSecureAuthorisationRequestRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string mid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string vpn_pswd;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string trans_id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string md;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string paRes;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public string options;
        
        public threeDSecureAuthorisationRequestRequest() {
        }
        
        public threeDSecureAuthorisationRequestRequest(string mid, string vpn_pswd, string trans_id, string md, string paRes, string options) {
            this.mid = mid;
            this.vpn_pswd = vpn_pswd;
            this.trans_id = trans_id;
            this.md = md;
            this.paRes = paRes;
            this.options = options;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="threeDSecureAuthorisationRequestResponse", WrapperNamespace="https://www.secpay.com/java-bin/services/SECCardService", IsWrapped=true)]
    public partial class threeDSecureAuthorisationRequestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string threeDSecureAuthorisationRequestReturn;
        
        public threeDSecureAuthorisationRequestResponse() {
        }
        
        public threeDSecureAuthorisationRequestResponse(string threeDSecureAuthorisationRequestReturn) {
            this.threeDSecureAuthorisationRequestReturn = threeDSecureAuthorisationRequestReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getReport", WrapperNamespace="http://secvpn.secpay.com", IsWrapped=true)]
    public partial class getReportRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string mid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string vpn_pswd;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string remote_pswd;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string report_type;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string cond_type;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public string condition;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=6)]
        public string currency;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=7)]
        public string predicate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=8)]
        public bool html;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=9)]
        public bool showErrs;
        
        public getReportRequest() {
        }
        
        public getReportRequest(string mid, string vpn_pswd, string remote_pswd, string report_type, string cond_type, string condition, string currency, string predicate, bool html, bool showErrs) {
            this.mid = mid;
            this.vpn_pswd = vpn_pswd;
            this.remote_pswd = remote_pswd;
            this.report_type = report_type;
            this.cond_type = cond_type;
            this.condition = condition;
            this.currency = currency;
            this.predicate = predicate;
            this.html = html;
            this.showErrs = showErrs;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getReportResponse", WrapperNamespace="https://www.secpay.com/java-bin/services/SECCardService", IsWrapped=true)]
    public partial class getReportResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string getReportReturn;
        
        public getReportResponse() {
        }
        
        public getReportResponse(string getReportReturn) {
            this.getReportReturn = getReportReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getTZReport", WrapperNamespace="http://secvpn.secpay.com", IsWrapped=true)]
    public partial class getTZReportRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string mid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string vpn_pswd;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string remote_pswd;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string report_type;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string cond_type;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public string condition;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=6)]
        public string currency;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=7)]
        public string predicate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=8)]
        public bool html;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=9)]
        public bool showErrs;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=10)]
        public string tz;
        
        public getTZReportRequest() {
        }
        
        public getTZReportRequest(string mid, string vpn_pswd, string remote_pswd, string report_type, string cond_type, string condition, string currency, string predicate, bool html, bool showErrs, string tz) {
            this.mid = mid;
            this.vpn_pswd = vpn_pswd;
            this.remote_pswd = remote_pswd;
            this.report_type = report_type;
            this.cond_type = cond_type;
            this.condition = condition;
            this.currency = currency;
            this.predicate = predicate;
            this.html = html;
            this.showErrs = showErrs;
            this.tz = tz;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getTZReportResponse", WrapperNamespace="https://www.secpay.com/java-bin/services/SECCardService", IsWrapped=true)]
    public partial class getTZReportResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string getTZReportReturn;
        
        public getTZReportResponse() {
        }
        
        public getTZReportResponse(string getTZReportReturn) {
            this.getTZReportReturn = getTZReportReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="performTransactionViaAlternatePaymentMethod", WrapperNamespace="http://secvpn.secpay.com", IsWrapped=true)]
    public partial class performTransactionViaAlternatePaymentMethodRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string mid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string vpn_pswd;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string paymentOrganisation;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string paymentMethod;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string paymentType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public string paymentRequestType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=6)]
        public string trans_id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=7)]
        public string amount;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=8)]
        public string currency;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=9)]
        public string options;
        
        public performTransactionViaAlternatePaymentMethodRequest() {
        }
        
        public performTransactionViaAlternatePaymentMethodRequest(string mid, string vpn_pswd, string paymentOrganisation, string paymentMethod, string paymentType, string paymentRequestType, string trans_id, string amount, string currency, string options) {
            this.mid = mid;
            this.vpn_pswd = vpn_pswd;
            this.paymentOrganisation = paymentOrganisation;
            this.paymentMethod = paymentMethod;
            this.paymentType = paymentType;
            this.paymentRequestType = paymentRequestType;
            this.trans_id = trans_id;
            this.amount = amount;
            this.currency = currency;
            this.options = options;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="performTransactionViaAlternatePaymentMethodResponse", WrapperNamespace="https://www.secpay.com/java-bin/services/SECCardService", IsWrapped=true)]
    public partial class performTransactionViaAlternatePaymentMethodResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string performTransactionViaAlternatePaymentMethodReturn;
        
        public performTransactionViaAlternatePaymentMethodResponse() {
        }
        
        public performTransactionViaAlternatePaymentMethodResponse(string performTransactionViaAlternatePaymentMethodReturn) {
            this.performTransactionViaAlternatePaymentMethodReturn = performTransactionViaAlternatePaymentMethodReturn;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SECVPNChannel : MrCMS.PaypointService.API.SECVPN, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SECVPNClient : System.ServiceModel.ClientBase<MrCMS.PaypointService.API.SECVPN>, MrCMS.PaypointService.API.SECVPN {
        
        public SECVPNClient() {
        }
        
        public SECVPNClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SECVPNClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SECVPNClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SECVPNClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MrCMS.PaypointService.API.refundCardFullResponse MrCMS.PaypointService.API.SECVPN.refundCardFull(MrCMS.PaypointService.API.refundCardFullRequest request) {
            return base.Channel.refundCardFull(request);
        }
        
        public string refundCardFull(string mid, string vpn_pswd, string trans_id, string amount, string remote_pswd, string new_trans_id) {
            MrCMS.PaypointService.API.refundCardFullRequest inValue = new MrCMS.PaypointService.API.refundCardFullRequest();
            inValue.mid = mid;
            inValue.vpn_pswd = vpn_pswd;
            inValue.trans_id = trans_id;
            inValue.amount = amount;
            inValue.remote_pswd = remote_pswd;
            inValue.new_trans_id = new_trans_id;
            MrCMS.PaypointService.API.refundCardFullResponse retVal = ((MrCMS.PaypointService.API.SECVPN)(this)).refundCardFull(inValue);
            return retVal.refundCardFullReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MrCMS.PaypointService.API.releaseCardFullResponse MrCMS.PaypointService.API.SECVPN.releaseCardFull(MrCMS.PaypointService.API.releaseCardFullRequest request) {
            return base.Channel.releaseCardFull(request);
        }
        
        public string releaseCardFull(string mid, string vpn_pswd, string trans_id, string amount, string remote_pswd, string new_trans_id) {
            MrCMS.PaypointService.API.releaseCardFullRequest inValue = new MrCMS.PaypointService.API.releaseCardFullRequest();
            inValue.mid = mid;
            inValue.vpn_pswd = vpn_pswd;
            inValue.trans_id = trans_id;
            inValue.amount = amount;
            inValue.remote_pswd = remote_pswd;
            inValue.new_trans_id = new_trans_id;
            MrCMS.PaypointService.API.releaseCardFullResponse retVal = ((MrCMS.PaypointService.API.SECVPN)(this)).releaseCardFull(inValue);
            return retVal.releaseCardFullReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MrCMS.PaypointService.API.repeatCardFullAddrResponse MrCMS.PaypointService.API.SECVPN.repeatCardFullAddr(MrCMS.PaypointService.API.repeatCardFullAddrRequest request) {
            return base.Channel.repeatCardFullAddr(request);
        }
        
        public string repeatCardFullAddr(string mid, string vpn_pswd, string trans_id, string amount, string remote_pswd, string new_trans_id, string exp_date, string order, string bill, string ship, string options) {
            MrCMS.PaypointService.API.repeatCardFullAddrRequest inValue = new MrCMS.PaypointService.API.repeatCardFullAddrRequest();
            inValue.mid = mid;
            inValue.vpn_pswd = vpn_pswd;
            inValue.trans_id = trans_id;
            inValue.amount = amount;
            inValue.remote_pswd = remote_pswd;
            inValue.new_trans_id = new_trans_id;
            inValue.exp_date = exp_date;
            inValue.order = order;
            inValue.bill = bill;
            inValue.ship = ship;
            inValue.options = options;
            MrCMS.PaypointService.API.repeatCardFullAddrResponse retVal = ((MrCMS.PaypointService.API.SECVPN)(this)).repeatCardFullAddr(inValue);
            return retVal.repeatCardFullAddrReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MrCMS.PaypointService.API.repeatCardFullResponse MrCMS.PaypointService.API.SECVPN.repeatCardFull(MrCMS.PaypointService.API.repeatCardFullRequest request) {
            return base.Channel.repeatCardFull(request);
        }
        
        public string repeatCardFull(string mid, string vpn_pswd, string trans_id, string amount, string remote_pswd, string new_trans_id, string exp_date, string order) {
            MrCMS.PaypointService.API.repeatCardFullRequest inValue = new MrCMS.PaypointService.API.repeatCardFullRequest();
            inValue.mid = mid;
            inValue.vpn_pswd = vpn_pswd;
            inValue.trans_id = trans_id;
            inValue.amount = amount;
            inValue.remote_pswd = remote_pswd;
            inValue.new_trans_id = new_trans_id;
            inValue.exp_date = exp_date;
            inValue.order = order;
            MrCMS.PaypointService.API.repeatCardFullResponse retVal = ((MrCMS.PaypointService.API.SECVPN)(this)).repeatCardFull(inValue);
            return retVal.repeatCardFullReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MrCMS.PaypointService.API.validateCardFullResponse MrCMS.PaypointService.API.SECVPN.validateCardFull(MrCMS.PaypointService.API.validateCardFullRequest request) {
            return base.Channel.validateCardFull(request);
        }
        
        public string validateCardFull(string mid, string vpn_pswd, string trans_id, string ip, string name, string card_number, string amount, string expiry_date, string issue_number, string start_date, string order, string shipping, string billing, string options) {
            MrCMS.PaypointService.API.validateCardFullRequest inValue = new MrCMS.PaypointService.API.validateCardFullRequest();
            inValue.mid = mid;
            inValue.vpn_pswd = vpn_pswd;
            inValue.trans_id = trans_id;
            inValue.ip = ip;
            inValue.name = name;
            inValue.card_number = card_number;
            inValue.amount = amount;
            inValue.expiry_date = expiry_date;
            inValue.issue_number = issue_number;
            inValue.start_date = start_date;
            inValue.order = order;
            inValue.shipping = shipping;
            inValue.billing = billing;
            inValue.options = options;
            MrCMS.PaypointService.API.validateCardFullResponse retVal = ((MrCMS.PaypointService.API.SECVPN)(this)).validateCardFull(inValue);
            return retVal.validateCardFullReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MrCMS.PaypointService.API.threeDSecureEnrolmentRequestResponse MrCMS.PaypointService.API.SECVPN.threeDSecureEnrolmentRequest(MrCMS.PaypointService.API.threeDSecureEnrolmentRequestRequest request) {
            return base.Channel.threeDSecureEnrolmentRequest(request);
        }
        
        public string threeDSecureEnrolmentRequest(
                    string mid, 
                    string vpn_pswd, 
                    string trans_id, 
                    string ip, 
                    string name, 
                    string card_number, 
                    string amount, 
                    string expiry_date, 
                    string issue_number, 
                    string start_date, 
                    string order, 
                    string shipping, 
                    string billing, 
                    string options, 
                    string device_category, 
                    string accept_headers, 
                    string user_agent, 
                    string mpi_merchant_name, 
                    string mpi_merchant_url, 
                    string mpi_description, 
                    string purchaseRecurringFrequency, 
                    string purchaseRecurringExpiry, 
                    string purchaseInstallments) {
            MrCMS.PaypointService.API.threeDSecureEnrolmentRequestRequest inValue = new MrCMS.PaypointService.API.threeDSecureEnrolmentRequestRequest();
            inValue.mid = mid;
            inValue.vpn_pswd = vpn_pswd;
            inValue.trans_id = trans_id;
            inValue.ip = ip;
            inValue.name = name;
            inValue.card_number = card_number;
            inValue.amount = amount;
            inValue.expiry_date = expiry_date;
            inValue.issue_number = issue_number;
            inValue.start_date = start_date;
            inValue.order = order;
            inValue.shipping = shipping;
            inValue.billing = billing;
            inValue.options = options;
            inValue.device_category = device_category;
            inValue.accept_headers = accept_headers;
            inValue.user_agent = user_agent;
            inValue.mpi_merchant_name = mpi_merchant_name;
            inValue.mpi_merchant_url = mpi_merchant_url;
            inValue.mpi_description = mpi_description;
            inValue.purchaseRecurringFrequency = purchaseRecurringFrequency;
            inValue.purchaseRecurringExpiry = purchaseRecurringExpiry;
            inValue.purchaseInstallments = purchaseInstallments;
            MrCMS.PaypointService.API.threeDSecureEnrolmentRequestResponse retVal = ((MrCMS.PaypointService.API.SECVPN)(this)).threeDSecureEnrolmentRequest(inValue);
            return retVal.threeDSecureEnrolmentRequestReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MrCMS.PaypointService.API.threeDSecureAuthorisationRequestResponse MrCMS.PaypointService.API.SECVPN.threeDSecureAuthorisationRequest(MrCMS.PaypointService.API.threeDSecureAuthorisationRequestRequest request) {
            return base.Channel.threeDSecureAuthorisationRequest(request);
        }
        
        public string threeDSecureAuthorisationRequest(string mid, string vpn_pswd, string trans_id, string md, string paRes, string options) {
            MrCMS.PaypointService.API.threeDSecureAuthorisationRequestRequest inValue = new MrCMS.PaypointService.API.threeDSecureAuthorisationRequestRequest();
            inValue.mid = mid;
            inValue.vpn_pswd = vpn_pswd;
            inValue.trans_id = trans_id;
            inValue.md = md;
            inValue.paRes = paRes;
            inValue.options = options;
            MrCMS.PaypointService.API.threeDSecureAuthorisationRequestResponse retVal = ((MrCMS.PaypointService.API.SECVPN)(this)).threeDSecureAuthorisationRequest(inValue);
            return retVal.threeDSecureAuthorisationRequestReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MrCMS.PaypointService.API.getReportResponse MrCMS.PaypointService.API.SECVPN.getReport(MrCMS.PaypointService.API.getReportRequest request) {
            return base.Channel.getReport(request);
        }
        
        public string getReport(string mid, string vpn_pswd, string remote_pswd, string report_type, string cond_type, string condition, string currency, string predicate, bool html, bool showErrs) {
            MrCMS.PaypointService.API.getReportRequest inValue = new MrCMS.PaypointService.API.getReportRequest();
            inValue.mid = mid;
            inValue.vpn_pswd = vpn_pswd;
            inValue.remote_pswd = remote_pswd;
            inValue.report_type = report_type;
            inValue.cond_type = cond_type;
            inValue.condition = condition;
            inValue.currency = currency;
            inValue.predicate = predicate;
            inValue.html = html;
            inValue.showErrs = showErrs;
            MrCMS.PaypointService.API.getReportResponse retVal = ((MrCMS.PaypointService.API.SECVPN)(this)).getReport(inValue);
            return retVal.getReportReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MrCMS.PaypointService.API.getTZReportResponse MrCMS.PaypointService.API.SECVPN.getTZReport(MrCMS.PaypointService.API.getTZReportRequest request) {
            return base.Channel.getTZReport(request);
        }
        
        public string getTZReport(string mid, string vpn_pswd, string remote_pswd, string report_type, string cond_type, string condition, string currency, string predicate, bool html, bool showErrs, string tz) {
            MrCMS.PaypointService.API.getTZReportRequest inValue = new MrCMS.PaypointService.API.getTZReportRequest();
            inValue.mid = mid;
            inValue.vpn_pswd = vpn_pswd;
            inValue.remote_pswd = remote_pswd;
            inValue.report_type = report_type;
            inValue.cond_type = cond_type;
            inValue.condition = condition;
            inValue.currency = currency;
            inValue.predicate = predicate;
            inValue.html = html;
            inValue.showErrs = showErrs;
            inValue.tz = tz;
            MrCMS.PaypointService.API.getTZReportResponse retVal = ((MrCMS.PaypointService.API.SECVPN)(this)).getTZReport(inValue);
            return retVal.getTZReportReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MrCMS.PaypointService.API.performTransactionViaAlternatePaymentMethodResponse MrCMS.PaypointService.API.SECVPN.performTransactionViaAlternatePaymentMethod(MrCMS.PaypointService.API.performTransactionViaAlternatePaymentMethodRequest request) {
            return base.Channel.performTransactionViaAlternatePaymentMethod(request);
        }
        
        public string performTransactionViaAlternatePaymentMethod(string mid, string vpn_pswd, string paymentOrganisation, string paymentMethod, string paymentType, string paymentRequestType, string trans_id, string amount, string currency, string options) {
            MrCMS.PaypointService.API.performTransactionViaAlternatePaymentMethodRequest inValue = new MrCMS.PaypointService.API.performTransactionViaAlternatePaymentMethodRequest();
            inValue.mid = mid;
            inValue.vpn_pswd = vpn_pswd;
            inValue.paymentOrganisation = paymentOrganisation;
            inValue.paymentMethod = paymentMethod;
            inValue.paymentType = paymentType;
            inValue.paymentRequestType = paymentRequestType;
            inValue.trans_id = trans_id;
            inValue.amount = amount;
            inValue.currency = currency;
            inValue.options = options;
            MrCMS.PaypointService.API.performTransactionViaAlternatePaymentMethodResponse retVal = ((MrCMS.PaypointService.API.SECVPN)(this)).performTransactionViaAlternatePaymentMethod(inValue);
            return retVal.performTransactionViaAlternatePaymentMethodReturn;
        }
    }
}
